version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: blog_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  web:
    build: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/blog_platform
      REDIS_URL: redis://redis:6379/0
      RAILS_ENV: production

  worker:
    build: .
    command: bundle exec sidekiq
    depends_on:
      - redis
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/blog_platform
      REDIS_URL: redis://redis:6379/0
